spring:
  application:
    name: workout-service  data:    mongodb:      uri: mongodb://localhost:27017/workoutdb
    
server:  port: 8090

eureka:  client:    service-url: 
      defaultZone: http://localhost:8761/eureka