server:  port: 8099
spring:
  cloud:
    gateway:
      routes:
      - id: workout-service
        uri: lb://workout-service
        predicates:        - Path= /wout/api/**        filters:        - StripPrefix=2      - id: gym-service        uri: lb://gym-service        predicates:        - Path= /gs/api/**        filters:        - StripPrefix=2        - name: MoreComplex          args:             complexMessage: secret complex message            times: 2